version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql   # persistent storage for database files
    networks:
      - employeenet

  employeeapi:
    build:
      context: .
      dockerfile: EmployeeApi/Dockerfile
    container_name: employeeapi
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=EmployeeDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;"
    depends_on:
      - sqlserver
   
    networks:
      - employeenet

  employeemvc:
    build:
      context: .
      dockerfile: EmployeeMvc/Dockerfile
    container_name: employeemvc
    ports:
      - "8082:3000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:3000
      BACKEND_URL: "http://employeeapi:8080"
    depends_on:
      - employeeapi
    networks:
      - employeenet

networks:
  employeenet:
    driver: bridge

volumes:
  sql_data:   #  volume for SQL Server persistence
